// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Provides AI-driven feedback on essay responses, focusing on grammar, vocabulary, coherence, and argumentation.
 *
 * - essayFeedback - A function that handles the essay feedback process.
 * - EssayFeedbackInput - The input type for the essayFeedback function.
 * - EssayFeedbackOutput - The return type for the essayFeedback function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const EssayFeedbackInputSchema = z.object({
  essay: z.string().describe('The essay to provide feedback on.'),
  topic: z.string().describe('The topic of the essay.'),
  instructions: z.string().optional().describe('Any specific instructions given for the essay.'),
});
export type EssayFeedbackInput = z.infer<typeof EssayFeedbackInputSchema>;

const EssayFeedbackOutputSchema = z.object({
  grammar: z.string().describe('Feedback on the grammar of the essay.'),
  vocabulary: z.string().describe('Feedback on the vocabulary used in the essay.'),
  coherence: z.string().describe('Feedback on the coherence and flow of the essay.'),
  argumentation: z.string().describe('Feedback on the argumentation presented in the essay.'),
  overallFeedback: z.string().describe('Overall feedback and suggestions for improvement.'),
});
export type EssayFeedbackOutput = z.infer<typeof EssayFeedbackOutputSchema>;

export async function essayFeedback(input: EssayFeedbackInput): Promise<EssayFeedbackOutput> {
  return essayFeedbackFlow(input);
}

const prompt = ai.definePrompt({
  name: 'essayFeedbackPrompt',
  input: {schema: EssayFeedbackInputSchema},
  output: {schema: EssayFeedbackOutputSchema},
  prompt: `You are an AI essay feedback assistant. Your task is to provide feedback on an essay based on the following criteria:\n\n*   Grammar: Identify and correct grammatical errors. Suggest improvements to sentence structure.\n*   Vocabulary: Assess the richness and appropriateness of the vocabulary. Suggest alternative word choices to enhance clarity and impact.\n*   Coherence: Evaluate the logical flow and organization of ideas. Provide recommendations on improving transitions and paragraph structure.\n*   Argumentation: Analyze the strength and validity of the arguments presented. Offer guidance on strengthening claims and providing evidence.\n\nEssay Topic: {{{topic}}}\nEssay Instructions (if any): {{{instructions}}}\nEssay: {{{essay}}}\n\nPlease provide detailed feedback in each of the following categories. Make sure to follow the EssayFeedbackOutputSchema output schema. The Zod descriptions there are instructions for what your output should contain. Focus on being helpful and actionable.
`,
});

const essayFeedbackFlow = ai.defineFlow(
  {
    name: 'essayFeedbackFlow',
    inputSchema: EssayFeedbackInputSchema,
    outputSchema: EssayFeedbackOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
